### ISSUE TITLE
Access to AShooterGameState

### ISSUE THREAD

**Issue by men232** [Michidu/ARK-Server-Beyond-API#2]
Hi, you making awesome project, thx.

My question is, how can i get access to AShooterGameState?
I need some data about the server like: session name, current online and max players.

**Comment by Michidu** [comment]
`AShooterGameState* state = static_cast<AShooterGameState*>(Ark::GetGameMode()->GetGameStateField());
	std::cout << state->GetServerSessionNameField().ToString() << "\n";`
