### ISSUE TITLE
Problem with hooks

### ISSUE THREAD

**Issue by men232** [Michidu/ARK-Server-Beyond-API#3]
I use this code to attach "InitWorld" but hooks doesn't call.
```c++
#include <Windows.h>
#include <iostream>
#include "API/Base.h"

#pragma comment(lib, "ArkApi.lib")

DECLARE_HOOK(UWorld_InitWorld, void, UWorld*, DWORD64);

void Init() {
	// Hooks
	Ark::SetHook("UWorld", "InitWorld", &Hook_UWorld_InitWorld, reinterpret_cast<LPVOID*>(&UWorld_InitWorld_original));
}

void _cdecl Hook_UWorld_InitWorld(UWorld* world, DWORD64 IVS) {
	std::cout << "Its work?" << std::endl;
	UWorld_InitWorld_original(world, IVS);
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved) {
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		Init();
		break;
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}
```

**Comment by Michidu** [comment]
API doesn't support multiple hooks of one function currently (InitWorld is already hooked inside the API itself).

**Comment by men232** [comment]
Is there any way to attach InitWorld in the plugin?

**Comment by Michidu** [comment]
Currently no but i will try to add support for multiple hooks. You can hook some other Init function for now.

**Comment by men232** [comment]
Where can I read the list of hooks?

I'm trying to get the UWorld by Ark::GetWorld() but as I understand it, I need to wait for Hook_UWorld_InitWorld

**Comment by Michidu** [comment]
You can hook any game function. Try this one: `void __cdecl AGameMode::InitGame(AGameMode *this, FString *MapName, FString *Options, FString *ErrorMessage)` it's called after InitWorld, so you should be able to to use Ark::GetWorld().

**Comment by men232** [comment]
Thx, it's work for my.
