### ISSUE TITLE
Get maxplayers of server

### ISSUE THREAD

**Issue by men232** [Michidu/ARK-Server-Beyond-API#4]
How can I get the maxplayers value of server?

**Comment by men232** [comment]
I try redefine AGameSession to get access to MaxPlayers field:

```C++
struct AGameSession {
	int GetMaxPlayersField() const { return GetNativeField<int>(this, "AGameSession", "MaxPlayers"); }
};
```

And them use this:
```c++
DECLARE_HOOK(AGameMode_InitGame, void, AGameMode*, FString*, FString*, FString*);

void Init() {
	// Hooks
	Ark::SetHook("AGameMode", "InitGame", &Hook_AGameMode_InitGame, reinterpret_cast<LPVOID*>(&AGameMode_InitGame_original));
}

void _cdecl Hook_AGameMode_InitGame(AGameMode* _AShooterGameMode, FString* MapName, FString* Options, FString* ErrorMessage) {
	AGameMode_InitGame_original(_AShooterGameMode, MapName, Options, ErrorMessage);

	int max_players = _AShooterGameMode->GetGameSessionField()->GetMaxSpectatorsField();
	std::cout << "Max players: " << max_players << std::endl;
}
```

And server crash. Maybe the game session still not initialized.
I'm not good in c++, I'm looking for your help :(

**Comment by Michidu** [comment]
Check the latest commit, i have added GameSession structure. You will also need to update config.json.
Now it works: ``std::cout << Ark::GetGameMode()->GetGameSessionField()->GetMaxPlayersField() << "\n";``

**Comment by men232** [comment]
thx, it's work

**Comment by men232** [comment]
Not it's crash
![screen shot 2017-09-20 at 19 36 27](https://user-images.githubusercontent.com/3619283/30655933-0a01ec68-9e3b-11e7-84b9-330f0b72f55a.png)
