### ISSUE TITLE
Give item with exact quality

### ISSUE THREAD

**Issue by men232** [Michidu/ARK-Server-Beyond-API#5]
Does the current api provide functional to give item with exact quality?

**Comment by Michidu** [comment]
AShooterPlayerController::GiveItem or AShooterPlayerController::GiveItemNum.

**Comment by men232** [comment]
If I want to give an item with "Mastercraft" quality what quality (float) value i should use?

**Comment by Michidu** [comment]
Yes, probably it won't give you Mastercraft item always. But those commands works exactly like console commands.
