### ISSUE TITLE
ASM Compatibility

### ISSUE THREAD

**Issue by bthppong** [Michidu/ARK-Server-Beyond-API#6]
I found when ASM updated and restart server.
Server with Beyond API don't close.

How to do
- Start server with ASM
- Stop with restart option
- After countdown old one didn't close but ASM start new old

Thank

PS. ASM = http://arkservermanager.freeforums.net/

**Comment by Michidu** [comment]
It works fine for me. I can stop server with "Stop" button. Maybe you were using an outdated version?
